<h1>Multiple Linear Regression</h1>

<h2>Table of Contents</h2>
<p>Make a prediction in several different ways by using PyTorch.</p>

<ul>
    <li><a href="#Prediction">Prediction</a></li>
    <li><a href="#Linear">Class Linear</a></li>
    <li><a href="#Cust">Build Custom Modules</a></li>
</ul>


<hr>

<h2>Preparation</h2>

Import the libraries and set the random seed.

In [1]:
# Import the libraries and set the random seed

from torch import nn
import torch
torch.manual_seed(1)

<!--Empty Space for separating topics-->

<h2 id="Prediction">Prediction</h2>

Set weight and bias.

In [2]:
# Set the weight and bias

w = torch.tensor([[2.0], [3.0]], requires_grad=True)
b = torch.tensor([[1.0]], requires_grad=True)

Define the parameters. <code>torch.mm</code> uses matrix multiplication instead of scaler multiplication.

In [3]:
# Define Prediction Function

def forward(x):
    yhat = torch.mm(x, w) + b
    return yhat

The function <code>forward</code> implements the following equation:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1_matrix_eq.png" width="600" alt="Matrix Linear Regression"/>

If we input a <i>1x2</i> tensor, because we have a <i>2x1</i> tensor as <code>w</code>, we will get a <i>1x1</i> tensor: 

In [4]:
# Calculate yhat

x = torch.tensor([[1.0, 2.0]])
yhat = forward(x)
print("The result: ", yhat)

The result:  tensor([[9.]], grad_fn=<AddBackward0>)


<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1example.png" width = "300" alt="Linear Regression Matrix Sample One" />

# Each row of the following tensor represents a sample:

In [5]:
# Sample tensor X

X = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])

In [6]:
# Make the prediction of X 

yhat = forward(X)
print("The result: ", yhat)

The result:  tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


<!--Empty Space for separating topics-->

<h2 id="Linear">Class Linear</h2>

We can use the linear class to make a prediction. You'll also use the linear class to build more complex models.

Let us create a model.

In [8]:
# Make a linear regression model using build-in function

model = nn.Linear(2, 1)

Make a prediction with the first sample:

In [9]:
# Make a prediction of x

yhat = model(x)
print("The result: ", yhat)

The result:  tensor([[-0.5754]], grad_fn=<AddmmBackward>)


Predict with multiple samples <code>X</code>: 

In [10]:
# Make a prediction of X

yhat = model(X)
print("The result: ", yhat)

The result:  tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward>)


The function performs matrix multiplication as shown in this image:

<img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1multi_sample_example.png" width = "600" alt="Linear Regression Matrix Sample One" />

<!--Empty Space for separating topics-->

<h2 id="Cust">Build Custom Modules </h2>

Now, you'll build a custom module. You can make more complex models by using this method later. 

In [11]:
# Create linear_regression Class

class linear_regression(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    # Prediction function
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

Build a linear regression object. The input feature size is two. 

In [12]:
model = linear_regression(2, 3)
X

tensor([[1., 1.],
        [1., 2.],
        [1., 3.]])

This will input the following equation:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1_matrix_eq.png" width="600" alt="Matrix Linear Regression" />

You can see the randomly initialized parameters by using the <code>parameters()</code> method:

In [13]:
# Print model parameters

print("The parameters: ", list(model.parameters()))

The parameters:  [Parameter containing:
tensor([[-0.1455,  0.3597],
        [ 0.0983, -0.0866],
        [ 0.1961,  0.0349]], requires_grad=True), Parameter containing:
tensor([ 0.2583, -0.2756, -0.0516], requires_grad=True)]


You can also see the parameters by using the <code>state_dict()</code> method:

In [14]:
# Print model parameters

print("The parameters: ", model.state_dict())

The parameters:  OrderedDict([('linear.weight', tensor([[-0.1455,  0.3597],
        [ 0.0983, -0.0866],
        [ 0.1961,  0.0349]])), ('linear.bias', tensor([ 0.2583, -0.2756, -0.0516]))])


Now we input a 1x2 tensor, and we will get a 1x1 tensor.

In [17]:
# Make a prediction of x

yhat = model(x)
print("The result: ", yhat)

The result:  tensor([[ 0.8323, -0.3504,  0.2143]], grad_fn=<AddmmBackward>)


The shape of the output is shown in the following image: 

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1_matrix_eq.png" width="600" alt="Matrix Linear Regression" />

Make a prediction for multiple samples:

In [30]:
# Make a prediction of X
model2 = linear_regression(4,2)
yhat = model2(X)
print("The result: ", yhat)
print(model2.state_dict())

The result:  tensor([[ 16.3724, -11.6547],
        [ 16.3724, -11.6547]], grad_fn=<AddmmBackward>)
OrderedDict([('linear.weight', tensor([[ 0.3313,  0.3116,  0.3553,  0.3163],
        [ 0.1291, -0.3419, -0.4199, -0.2291]])), ('linear.bias', tensor([-0.0582, -0.3065]))])


The shape is shown in the following image: 


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.6.1Multi_sample.png" width="600" alt="Multiple Samples Linear Regression" />

<!--Empty Space for separating topics-->

<h3>Practice</h3>

Build a model or object of type <code>linear_regression</code>. Using the <code>linear_regression</code> object will predict the following tensor: 

In [31]:
# Practice: Build a model to predict the follow tensor.

X = torch.tensor([[11.0, 12.0, 13, 14], [11, 12, 13, 14]])
model2 = linear_regression(4,2)
yhat = model2(X)
print(yhat)

tensor([[5.5762, 7.3898],
        [5.5762, 7.3898]], grad_fn=<AddmmBackward>)


<!--Empty Space for separating topics-->

<hr>